### ISSUE TITLE
Refresh button not working on 

### ISSUE THREAD

**Issue by herbieforever** [robinsving/pf2e-item-revitalizer#26]
I just upgraded to v 1.30. When I use the Revitalize button in an NPC sheet, the first action to refresh the item to the upgraded version is not available for all items on all NPCs. When I mouse over the button, it reads "Not available on this item (Rule Engine or Actor Type prevents Refresh). Recreate item, or check the module settings for potential backup Refresh option."  The refresh button works on PC sheets in the Game World. Reading the Changelog it appears that refreshing is now only available on PC sheets? Why? The only reason I use the module is to update spells to the Remastered version on NPCs. Is there a way to do this now using this module? Otherwise the module isn't helpful anymore. Sorry to post this here as it might be feedback rather than a question, but only place to interact with module creator.

**Comment by robinsving** [comment]
Hi @herbieforever

I removed it after a discussion with the developers of the PF2e system, where Items are ruined when Refreshed using the built-in Refresher (which is the one my module is calling). Especially when used on Feats and Spells.

Until _they_ have fixed this in the system then I'd rather be safe than sorry.

If this removes all usage of this module for you, then that saddens me, but I'd rather have that than users getting unusable spells due to my module (and this PF2e system bug).

Hopefully, you can use this module to determine the Spells that are outdated, and then manually update them using the Refresh (since this feature is not blocked, despite the PF2e devs saying that it is not meant for NPCs) but I would caution you to _manually recheck all the Refreshed Items_ since they may be ruined by the built-in Refresh.

I hope that this makes sense to you

**Comment by robinsving** [comment]
Here's the bug in question. https://github.com/foundryvtt/pf2e/issues/17573

If they fix this, which seems unlikely seeing as they just closed the issue, I will be more than happy to readd the feature

**Comment by herbieforever** [comment]
I understand. Bummer that Tmun isn't able to fix it. I noticed some items
break from time to time when I'd refresh, especially some monster
abilities. But it was helpful for upgrading spells quickly on NPCs. Will
just have to do it manually. Thanks for your reply.

**Comment by Steven-Soult-Jr** [comment]
It was definitely the case that monster abilities, when refreshed, would reset to their default values. That includes things like frightening presence, tremorsense, etc. They would have 0 radius or remove special information like "claw only" on reactive strike. But refreshing equipment and spells worked fine.

Is there a way to disable refreshing just items from the bestiary ability glossary instead of disabling everything on NPCs? Or include a check box for advanced users in the settings who understand the risks?

I would rather refresh then edit my abilities back to their proper range than not be able to do it at all.

**Comment by robinsving** [comment]
Sounds like a good idea. Will check to make sure that this is only the case for Bestiary compendium. But at least equipment should be fine.
V
Will get back when I have had the time for this

**Comment by robinsving** [comment]
Hmm, there seems to be another bug for NPCs that I had not seen before. If you add an Item to an NPC in a scene, then my module will try to check for Refreshing using the "default" NPC version, since this is what exists in Foundry's `game.actors`. I will need to put some more time into this

**Comment by robinsving** [comment]
OK, a new version 1.31.0 is out. Please take a look.

Notable changes:
- NPC tokens now Revitalize the correct Sheet (Token, rather than Actor)
- @Check, and X reach in description will not be validated anymore. There are sometimes not set in the Compendium.
- NPCs can now Refresh, provided that the Origin Source is not the Bestiary
- Better feedback to user, if Origin is Bestiary
