### ISSUE TITLE
Request : look for rules element

### ISSUE THREAD

**Issue by uniwars** [robinsving/pf2e-item-revitalizer#9]
Hi, if I'm not mistaking the module doesn't check the difference between rule elements of an item, would that be possible to handle that ?

**Comment by robinsving** [comment]
It is a thing I am working on. The rule object is a bit more annoying to handle, as PF2e does things like remove properties when copied to Actors' sheets. It will be out as a part of the next version, for sure

**Comment by robinsving** [comment]
This is implemented in 1.1.0. Please check

**Comment by uniwars** [comment]
it seems to work fine for feats, but not with class feature :

I tried to remove a letter from my weapon legend class feature (removed the last m of polearm at the end of the first RE) and it doesn't find it

**Comment by robinsving** [comment]
level, price, etc. are not measured currently. Some things are due to the way that PF2e handles the copying, some due to me not having the time to do proper testing. Nor are titles of the items.

As for the others, there are a lot of rule elements. I am currently trying to figure out which ones are actually useful.
RE "selection" is not useful, as that one is added when putting the Item to the sheet (and this doesn't exist in the Compendium version).

My principle is the caution approach. Rather avoiding false positives than false negatives. Please report any more things you think _should_ be added, and I will look into them

**Comment by uniwars** [comment]
I found one more thing outdated on my PC with the last release, thanks

The list of thing I think should be looked at :

- Price, it happens that original implementation of an item by the system has a wrong price
- Level, for the same reason
- Weapon traits because some got errata
- Weapon base dice damage for the same reason
- Spell base damage and heightened effect for the same reason
- Spell traits, action cost, duration, cast time, range, school in prevision for remastered edition

**Comment by robinsving** [comment]
I see that with these requirements I will have to rethink some things regarding the filtering I am doing. 
Level is, for instance not possible for 'class feats' as they have the lowest level where any feat can access them (Resolve, for instance,  is granted at lvl 11 for some classes but at 7 for others).

I will rewrite the module to handle items differently based om Item type, and see what comes out of that.

**Comment by uniwars** [comment]
Oh yes, level and price only for equipment

**Comment by robinsving** [comment]
Hi @uniwars 
Please check version 1.4.0.
I consider RE to be in place (though I expect a lot of errors this early in development). I'd be happy to hear from you again for any errors that you can find with the rule sets.
